# Part 2

In [1]:
import os
import time
import numpy as np
import matplotlib.pyplot as plt 
import scipy
import scipy.io as spio
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
import math
import urllib
from urllib.request import urlopen
%matplotlib inline
import urllib.request
import datetime as dt
from datetime import datetime
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
import pandas as pd

In [21]:
def generate_data(m,n):
    data = np.random.uniform(low=-1, high=1, size=(m,(n+1)))
    data = np.sign(data)
    return data

def add_bias(x):
    x_with_bias = np.ones((x.shape[0],x.shape[1]+1))
    x_with_bias[:,:-1] = x
    return x_with_bias

In [8]:
df = generate_data(4,3)

In [9]:
df

array([[ 1., -1., -1.,  1.],
       [ 1.,  1.,  1., -1.],
       [ 1.,  1., -1.,  1.],
       [-1.,  1.,  1., -1.]])

## Binary Perceptron

In [131]:
# Binary perceptron algorithm 
# Learning rate? 
def perceptron_train(x,y,max_epoch=20, tol=0.01, learning_rate=1):
    m = x.shape[0] #number of examples
    n = x.shape[1] #number of features
    x = add_bias(x)
    error_per_epoch = np.zeros(max_epoch)
    errors = np.zeros(m)
    W = np.zeros(n+1)
    
    num_errors = 0 
    
    for epoch in range(max_epoch):
        #print('epoch=',epoch)
        errors = np.zeros(m)
        num_errors = 0 #This should be bounded..? Maybe calculate the bound in the explanation
    
        #iterate through training set
        for t in range(m):
            x_t = x[t,:]
            y_t = y[t]
            pred_t = np.sign(W@x_t) #0 to begin with 
    
            if pred_t*y_t<=0:
                #print('t=',t)
                #print('error! y_lab=', y_t)
                num_errors +=1
                W = W + learning_rate*x_t.T*y_t
                errors[t] = num_errors 
                #print('W=',W)
                
        error_per_epoch[epoch] = num_errors
        #print(epoch, 'error=',errors[-1])
        
        #print('current_error_rate', error_per_epoch)
        
        if epoch>1:
            #print('old_error=',error_per_epoch[epoch-1])
            #print('new_error=',error_per_epoch[epoch])
            diff_rates = (error_per_epoch[epoch-1] - error_per_epoch[epoch])/m
 
            #Stop if the error rate has increased, 
            #or the difference in error rate between the previous one and the current one < tolerance. 
            if error_per_epoch[epoch]/m < 0.05:
                print('error rate< 10%')
                if diff_rates<tol:
                    print('converging')
                elif diff_rates<0:
                    print('error increased')
                elif error_per_epoch[epoch]==0:
                    print('no error')
                    break
        
    return W, error_per_epoch[:epoch+1]


def perceptron_test(x_test,y_test,W):
    x_test = add_bias(x_test)
    m_test = x_test.shape[0]
    pred = np.sign(x_test@W) #(n,1) x (m_test,n)
    diff = pred - y_test
    mistakes = len(diff[diff!=0])   
    return mistakes,pred

In [128]:
df = generate_data(40,30)
x = df[:,0:-1]
y = df[:,-1]
W, error_per_epoch = perceptron_train(x,y,max_epoch=30, tol=0.01, learning_rate=1)

error rate< 10%
error rate< 10%
no error


In [132]:
mistakes,pred = perceptron_test(x[:10],y[:10],W)

In [126]:
error_per_epoch
### Does not seem to converge for some combination of x and y. 

array([28., 19., 15., 14., 11.,  8., 11.,  8., 14.,  7.,  7.,  8.,  7.,
        5.,  8.,  6.,  3.,  7.,  0.])

## Winnow

In [199]:
def winnow_train(x,y,max_epoch=20,tol=0.01, learning_rate=1,gamma_bound=0.5):
    m = x.shape[0] #number of examples
    n = x.shape[1] #number of features
    error_per_epoch = np.zeros(max_epoch)
    errors = np.zeros(m)
    W = np.ones(n)
    mistake_bound = (n/gamma_bound)**2
    num_errors = 0 
    
    for epoch in range(max_epoch):
        
        errors = np.zeros(m)
        num_errors = 0 #This should be bounded..? Maybe calculate the bound in the explanation
        print('epoch=',epoch)
        #iterate through training set
        for t in range(m):
            
            x_t = x[t,:]
            y_t = y[t]
            gamma = W@x_t
            
            if gamma>=gamma_bound:
                pred_t = 1
            else:
                pred_t = -1
            
            if pred_t != y_t:
                print('error!')
                #print('pred=',pred_t)
                print('y_t=',y_t)
                num_errors+=1
                power = (y_t - pred_t)*x_t/2 #1 when error made on positive class, -1 when error made on negative class
                print('ratio of update of W',2**power)
                W += W*(2**power) #element wise multiplication, and element wise power
                
                #Once weight>n, it should no longer change. 
                W[W>n] = n
                print(W)
                errors[t] = num_errors
                print('current error',num_errors)
                #print('W=',W)
                
        error_per_epoch[epoch] = num_errors
        
        if epoch>1:
            diff_rates = (error_per_epoch[epoch-1] - error_per_epoch[epoch])/m
            
            #Stop if the error rate has increased, 
            #or the difference in error rate between the previous one and the current one < tolerance. 
            if error_per_epoch[epoch]/m < 0.05:
                print('error rate< 10%')
                if diff_rates<tol:
                    print('converging')
                elif diff_rates<0:
                    print('error increased')
                elif error_per_epoch[epoch]==0:
                    print('no error')
                    break
    
    return W, error_per_epoch[:epoch+1]


def winnow_test(x_test,y_test,W,gamma=0):
    m_test = x_test.shape[0]
    gamma = W@x_t
    if gamma>=n:
        pred_t = 1
    else:
        pred_t = -1
    diff = pred - y_test
    mistakes = len(diff[diff!=0])  
    return mistakes,pred

In [202]:
df = generate_data(40,30)
x = df[:,0:-1]
y = df[:,-1]
W, error_per_epoch = winnow_train(x,y,max_epoch=20,tol=0.01, learning_rate=1,gamma_bound=0.1)

epoch= 0
error!
y_t= 1.0
ratio of update of W [2.  0.5 2.  2.  0.5 0.5 2.  0.5 2.  0.5 2.  2.  0.5 0.5 0.5 2.  0.5 0.5
 2.  0.5 0.5 0.5 0.5 0.5 0.5 2.  2.  0.5 2.  0.5]
[3.  1.5 3.  3.  1.5 1.5 3.  1.5 3.  1.5 3.  3.  1.5 1.5 1.5 3.  1.5 1.5
 3.  1.5 1.5 1.5 1.5 1.5 1.5 3.  3.  1.5 3.  1.5]
current error 1
error!
y_t= 1.0
ratio of update of W [0.5 2.  0.5 2.  0.5 2.  2.  2.  0.5 2.  0.5 0.5 0.5 0.5 0.5 0.5 0.5 2.
 0.5 0.5 0.5 2.  0.5 2.  0.5 2.  2.  0.5 0.5 2. ]
[4.5  4.5  4.5  9.   2.25 4.5  9.   4.5  4.5  4.5  4.5  4.5  2.25 2.25
 2.25 4.5  2.25 4.5  4.5  2.25 2.25 4.5  2.25 4.5  2.25 9.   9.   2.25
 4.5  4.5 ]
current error 2
error!
y_t= -1.0
ratio of update of W [0.5 0.5 2.  0.5 0.5 0.5 0.5 0.5 2.  2.  2.  2.  2.  2.  2.  0.5 0.5 2.
 0.5 0.5 2.  2.  2.  0.5 2.  2.  0.5 0.5 2.  2. ]
[ 6.75   6.75  13.5   13.5    3.375  6.75  13.5    6.75  13.5   13.5
 13.5   13.5    6.75   6.75   6.75   6.75   3.375 13.5    6.75   3.375
  6.75  13.5    6.75   6.75   6.75  27.    13.5    3.375 13.5  

error!
y_t= 1.0
ratio of update of W [2.  0.5 0.5 0.5 2.  2.  2.  0.5 0.5 2.  0.5 2.  2.  0.5 2.  2.  0.5 2.
 0.5 0.5 0.5 0.5 0.5 0.5 2.  0.5 2.  0.5 2.  0.5]
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
current error 11
error!
y_t= -1.0
ratio of update of W [0.5 0.5 0.5 2.  0.5 2.  0.5 0.5 2.  2.  0.5 2.  0.5 2.  0.5 2.  2.  0.5
 2.  0.5 2.  2.  0.5 0.5 0.5 0.5 2.  0.5 0.5 2. ]
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
current error 12
error!
y_t= 1.0
ratio of update of W [2.  0.5 0.5 0.5 0.5 0.5 2.  2.  0.5 2.  0.5 2.  2.  0.5 2.  0.5 0.5 2.
 0.5 0.5 0.5 0.5 2.  2.  0.5 2.  2.  2.  2.  0.5]
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
current error 13
error!
y_t= -1.0
ratio of update of W [2.  0.5 0.5 0.5 2.  2.  0.5 2.  2.  0.5 0.5 0.5 2.  2.  2.  0.

error!
y_t= -1.0
ratio of update of W [0.5 0.5 0.5 2.  0.5 0.5 0.5 2.  0.5 0.5 0.5 0.5 2.  0.5 0.5 2.  2.  0.5
 2.  2.  2.  0.5 2.  2.  0.5 0.5 2.  2.  0.5 0.5]
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
current error 4
error!
y_t= -1.0
ratio of update of W [2.  0.5 0.5 0.5 2.  0.5 0.5 0.5 2.  2.  0.5 0.5 2.  2.  0.5 2.  2.  0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 2.  2.  2.  0.5]
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
current error 5
error!
y_t= -1.0
ratio of update of W [2.  2.  2.  0.5 0.5 0.5 0.5 2.  2.  0.5 2.  0.5 0.5 2.  0.5 0.5 0.5 0.5
 0.5 0.5 2.  2.  0.5 2.  0.5 0.5 0.5 0.5 0.5 0.5]
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
current error 6
error!
y_t= -1.0
ratio of update of W [0.5 0.5 0.5 2.  0.5 0.5 2.  2.  0.5 0.5 2.  2.  0.5 0.5 2.  2

In [203]:
error_per_epoch 

array([17., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15., 15., 15.])

In [192]:
W

array([6.90572950e+099, 1.10491672e+101, 1.19795311e+082, 1.53337998e+084,
       2.63432674e+094, 6.90572950e+099, 4.11613554e+092, 3.21573089e+090,
       6.13351991e+084, 2.76229180e+100, 6.13351991e+084, 1.38114590e+100,
       1.38114590e+100, 3.29290843e+093, 1.38114590e+100, 1.72643237e+099,
       1.05373070e+095, 1.05373070e+095, 1.38114590e+100, 9.81363186e+085,
       5.52458360e+100, 1.38114590e+100, 2.76229180e+100, 1.72643237e+099,
       2.76229180e+100, 2.76229180e+100, 6.90572950e+099, 9.81363186e+085,
       7.48720692e+080, 2.76229180e+100])

In [ ]:
# Least Squares Regression

In [ ]:
# 1 Nearest Neighbors